---
application:
  name: "ackee"
  project: "my-app"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "name"
  version: "12"
routers:
- name: "main-ackee"
  routes:
  - application_name: "ackee"
    paths:
    - "/*"
