[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"
  environment = {
    NODE_VERSION = "14.9.0"
    NODE_ENV = "production"
  }
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true
[template]
  [template.environment]
    ACKEE_ACKEE_MONGODB = "MongoDB connection URI"
    ACKEE_USERNAME = "Username used to protect the interface"
    ACKEE_PASSWORD = "Password used to protect the interface"
    ACKEE_ALLOW_ORIGIN = "Custom CORS headers like 'https://a.example.com,https://b.example.com'"