[build]
  publish = "dist"
  command = "yarn build"
  functions = "functions/"
  environment = {
    NODE_VERSION = "14.9.0"
    NODE_ENV = "production"
  }
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true